version: 0.1
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - aws s3 sync --delete . "s3://gholt-personal-website"
 post_build:
   commands:
     - echo "post_build step"
